spring.application.name=spring-ecommerce
server.port=8080

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:test

spring.sql.init.mode=always

security.jwt.token.secret-key=${JWT_SECRET_KEY}
security.jwt.token.expire-length=3600000


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

stripe.secret-key=${STRIPE_SECRET_KEY}
