spring.application.name=spring-ecommerce

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:test
spring.sql.init.mode=always

stripe.secret-key=${STRIPE_SECRET_KEY}

security.jwt.token.secret-key=${JWT_SECRET}
security.jwt.token.expire-length=${JWT_TIME:3600000}  # default 1h if not set

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:*}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false