spring.application.name=spring-ecommerce

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:database
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

stripe.secret-key=${STRIPE_SECRET_KEY}
security.jwt.token.secret-key=${SECURITY_JWT_TOKEN_SECRET-KEY}
security.jwt.token.expire-length=${SECURITY_JWT_TOKEN_EXPIRE-LENGTH}
