
    create table cart_items (
        cart_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_option_id bigint not null,
        quantity bigint not null,
        primary key (id),
        unique (cart_id, product_option_id)
    );

    create table carts (
        id bigint generated by default as identity,
        member_id bigint not null,
        primary key (id)
    );

    create table members (
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        name varchar(255) not null,
        password varchar(255) not null,
        role varchar(255) not null,
        primary key (id)
    );

    create table options (
        id bigint generated by default as identity,
        product_id bigint not null,
        quantity bigint not null,
        name varchar(255) not null,
        primary key (id),
        constraint uk_product_option_product_name unique (product_id, name)
    );

    create table order_items (
        price float(53) not null,
        quantity integer not null,
        id bigint generated by default as identity,
        order_id bigint not null,
        product_option_id bigint not null,
        primary key (id)
    );

    create table orders (
        id bigint generated by default as identity,
        member_id bigint not null,
        order_date_time timestamp(6) not null,
        status enum ('PAID','PENDING') not null,
        primary key (id)
    );

    create table payments (
        amount bigint not null,
        id bigint generated by default as identity,
        order_id bigint not null unique,
        currency varchar(255) not null,
        failure_reason varchar(255),
        payment_method varchar(255),
        status varchar(255) not null,
        stripe_session_id varchar(255) not null,
        primary key (id)
    );

    create table products (
        price float(53) not null,
        id bigint generated by default as identity,
        product_id bigint,
        image_url varchar(255) not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists cart_items 
       add constraint FKpcttvuq4mxppo8sxggjtn5i2c 
       foreign key (cart_id) 
       references carts;

    alter table if exists cart_items 
       add constraint FK3n7mse6kxcpyr5nc586k8lkm3 
       foreign key (product_option_id) 
       references options;

    alter table if exists options 
       add constraint FK2m37jcoh1yt06dsivrphak718 
       foreign key (product_id) 
       references products;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FK4xadyroqpvg8ebvhdcdv28nac 
       foreign key (product_option_id) 
       references options;

    alter table if exists payments 
       add constraint FK81gagumt0r8y3rmudcgpbk42l 
       foreign key (order_id) 
       references orders;

    alter table if exists products 
       add constraint FK5syljt40nomyb29umdshbvul5 
       foreign key (product_id) 
       references members;
